baseURL = "https://cgp05.github.io/"
languageCode = "en-us"
title = "Christian P."
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.homeInfoParams]
Title = "Welcome"
Content = """
Economics and Applied Statistics student at the [University of Toronto Mississauga](https://utm.utoronto.ca/).  
Skilled at econometrics and statistical analysis.  
I also build civic tech projects with Python, R, and SQL on [my GitHub](https://github.com/cgp05).
"""

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "/portfolio/"
weight = 20

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 24

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 25