baseURL = "https://cgp05.github.io/"
languageCode = "en-us"
title = "Christian P."
theme = "PaperMod"

[params.homeInfoParams]
Title = "Welcome"
Content = "Student | Essays | Projects"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Essays"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 30
